{{- if .Values.wavefront.token }}
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: collector
  name: {{ template "common.names.fullname" . }}
type: Opaque
data:
  api-token: {{ .Values.wavefront.token | b64enc | quote }}
{{- end }}
