{{- if and .Values.collector.enabled (not .Values.collector.useDaemonset) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: collector
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ template "common.names.fullname" . }}-collector
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: collector
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: collector
    spec:
      serviceAccountName: {{ template "wavefront.collector.serviceAccountName" . }}
      containers:
      - name: wavefront-collector
        image: {{ template "wavefront.collector.image" . }}
        imagePullPolicy: {{ .Values.collector.image.pullPolicy }}
        command:
        - wavefront-collector
        - --daemon=false
        - --config-file=/etc/collector/config.yaml
        {{- if .Values.collector.maxProcs }}
        - --max-procs={{ .Values.collector.maxProcs }}
        {{- end }}
        {{- if .Values.collector.logLevel }}
        - --log-level={{ .Values.collector.logLevel }}
        {{- end }}
        {{- if .Values.collector.resources}}
        resources: {{ toYaml .Values.collector.resources | indent 10 }}
        {{- end }}
    {{- if .Values.collector.priorityClassName }}
      priorityClassName: {{ .Values.collector.priorityClassName }}
    {{- end }}
    {{- if .Values.collector.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.collector.tolerations "context" .) | nindent 8 }}
    {{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/collector/
          readOnly: true
        - name: ssl-certs
          mountPath: /etc/ssl/certs
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: {{ template "common.names.fullname" . }}-collector-config
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs
{{- end }}
