{{- if and .Values.rbac.create .Values.collector.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: collector
  name: {{ template "common.names.fullname" . }}-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "common.names.fullname" . }}-collector
subjects:
  - kind: ServiceAccount
    name: {{ template "wavefront.collector.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
