{{- if and .Values.collector.enabled .Values.collector.useDaemonset }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: collector
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ template "common.names.fullname" . }}-collector
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: collector
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: collector
    spec:
      tolerations:
        - effect: NoSchedule
          key: node.alpha.kubernetes.io/role
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
    {{- if .Values.collector.tolerations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.collector.tolerations "context" .) | nindent 6 }}
    {{- end }}
      serviceAccountName: {{ template "wavefront.collector.serviceAccountName" . }}
      containers:
        - name: wavefront-collector
          image: {{ template "wavefront.collector.image" . }}
          imagePullPolicy: {{ .Values.collector.image.pullPolicy }}
          command:
            - wavefront-collector
            - --daemon=true
            - --config-file=/etc/collector/config.yaml
            {{- if .Values.collector.maxProcs }}
            - --max-procs={{ .Values.collector.maxProcs }}
            {{- end }}
            {{- if .Values.collector.logLevel }}
            - --log-level={{ .Values.collector.logLevel }}
            {{- end }}
          env:
            - name: HOST_PROC
              value: /host/proc
            - name: POD_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8088
              protocol: TCP
          {{- if .Values.collector.resources }}
          resources: {{- toYaml .Values.collector.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.collector.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.collector.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.collector.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.collector.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: procfs
              mountPath: /host/proc
              readOnly: true
            - name: config
              mountPath: /etc/collector/
              readOnly: true
    {{- if .Values.collector.priorityClassName }}
      priorityClassName: {{ .Values.collector.priorityClassName }}
    {{- end }}
      volumes:
        - name: procfs
          hostPath:
            path: /proc
        - name: config
          configMap:
            name: {{ template "common.names.fullname" . }}-collector-config
{{- end }}
