{{- if .Values.proxy.preprocessor }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  name: {{ template "common.names.fullname" . }}-proxy-preprocessor
data:
{{ tpl (toYaml .Values.proxy.preprocessor) . | indent 2 }}
{{- end }}
